name: Release

on:
  push:
    branches: [master, alpha, beta]

# Only allow one release workflow to execute at a time, since each release
# workflow uses shared resources (git tags, package registries)
concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Compile TypeScript
        run: npm run build
      - name: Run tests
        run: npm run --workspaces test
      - name: Check docs for accuracy
        run: git diff --exit-code './**/docs/**'
      - name: Release
        run: |
          find . -name 'index.js' | grep @semantic-release/npm/index.js | xargs -I {} npx patch-semantic-release-npm-for-msr --file {}
          npx multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
